Update publish.sh
aws/eks-distro pull request #47
Opened 2020-12-01 20:12 UTC by abhinavmpandey08

*Issue #, if available:*

*Description of changes:*
Create new invalidation to invalidate the cloudfront distribution

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-12-01 20:15 UTC, micahhausler requested changes

2020-12-01 20:15 UTC, micahhausler commented on docs/publish.sh
> +aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths '/*'
Can you  set `DISTRIBUTION_ID=${DISTRIBUTION_ID:-"E1G9R70424D2RN"}` above?

2020-12-01 20:17 UTC, micahhausler commented on docs/publish.sh
> +aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths '/*'
Can you also set the paths to 
```
/404.html /assets/ /community/ /index.html /search/ /sitemap.xml /sitemap.xml.gz/users/
```

2020-12-01 20:17 UTC, micahhausler commented
/hold

Wait to unhold until permissions are updated

2020-12-02 01:16 UTC, micahhausler approved these changes
/lgtm
/approve

2020-12-02 01:43 UTC, micahhausler commented
/unhold

2020-12-02 06:01 UTC, marceloboeira approved these changes

2020-12-02 12:51 UTC, merged