Updated coredns version and added README
aws/eks-distro pull request #646
Opened 2021-12-15 07:01 UTC by kschumy

*Issue #, if available:*

*Description of changes:*
* Updated coredns version to be 1.8.4 for all versions.
* Added README about updating coredns
* Updated attribution
* Updated CHECKSUMS
* Updated Golang version: https://github.com/coredns/coredns/blob/053c4d5ca1772517746a854e87ffa971249df14b/go.mod#L3

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-12-15 16:26 UTC, jaxesn requested changes
This looks pretty good. Not sure why the checksums arent matching, curious how you generated these?

Youll also need to change this, https://github.com/aws/eks-distro/blob/main/development/kops/cluster_wait.sh#L41, probably can just remove the if all together now that its the same for all versions.

2021-12-16 01:37 UTC, kschumy commented
> This looks pretty good. Not sure why the checksums arent matching, curious how you generated these?
> 
> Youll also need to change this, https://github.com/aws/eks-distro/blob/main/development/kops/cluster_wait.sh#L41, probably can just remove the if all together now that its the same for all versions.

We're going to apply the patch added to 1.20 and 1.21 to 1.18 and 1.19. See  PR #547. So for this PR, I removed the if condition related to kops in cluster_wait.sh  and deleted core_dns_cluster_role.yaml

2021-12-16 02:37 UTC, kschumy commented
/ hold

The versions may not be correct. I'm looking into this

2021-12-16 04:57 UTC, kschumy commented
/hold

See last comment

2021-12-16 22:30 UTC, jaxesn commented on projects/coredns/coredns/Makefile
> +GOLANG_VERSION?=1.16
```suggestion
GOLANG_VERSION?=$(shell cat $(RELEASE_BRANCH)/GOLANG_VERSION)
```

2021-12-17 01:18 UTC, jaxesn requested changes

2021-12-17 01:18 UTC, jaxesn commented on projects/coredns/coredns/Makefile
> +GOLANG_VERSION?=$(shell cat ./$(RELEASE_BRANCH)/GOLANG_VERSION)
Remove the ./ Just to be consistent with the one above.

2021-12-17 01:18 UTC, jaxesn commented on projects/coredns/coredns/1-19/ATTRIBUTION.txt
> +https://github.com/googleapis/google-cloud-go
Rever this change

2021-12-17 01:42 UTC, jaxesn approved these changes
/lgtm

2021-12-17 01:45 UTC, merged