Update kops docs
aws/eks-distro pull request #91
Opened 2020-12-17 23:06 UTC by TerryHowe

Document changes for new kOps scripts

2020-12-17 23:06 UTC, TerryHowe commented
/hold

2020-12-23 02:30 UTC, micahhausler requested changes
One nit

2020-12-23 02:30 UTC, micahhausler commented on development/kops/README.md
> +It may take a while for the cluster. You can use the `cluster_waith.sh`
```suggestion
It may take a while for the cluster. You can use the `cluster_wait.sh`
```

2020-12-23 02:39 UTC, TerryHowe commented on development/kops/README.md
> +It may take a while for the cluster. You can use the `cluster_waith.sh`
Fixed, thanks!

2020-12-24 23:29 UTC, abhay-krishna commented
/lgtm
/approve

2020-12-24 23:40 UTC, abhay-krishna approved these changes

2020-12-24 23:45 UTC, merged